# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 1 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  autocheckin:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      
      - name: Setup Node.js v16.x
        uses: actions/setup-node@v2
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: 16.x
        
      - name: Auto CheckIn
        run: |
          npm i
          node src/index.js ${{secrets.HUA_AID}} ${{secrets.HUA_UUID}} ${{secrets.SPIDER}} ${{secrets.SIGNATURE}} ${{secrets.HUA_SESSION_ID}} ${{secrets.PUSH_SESSION_TOKEN}}
          
      - name: Keepalive Workflow
        uses: gautamkrishnar/keepalive-workflow@1.1.0
